language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
# command to install dependencies
env:
    - DJANGO=3.0
    - DJANGO=3.1

install:
    - pip install -q --upgrade pip
    - pip install -q Django==$DJANGO;
    - pip install -q -e .

# command to run tests
script: nosetests
